"""
src/ingestion.py - Phase 2: Loading Semantic AI JSONs

Workflow:
  1. This skips all yt-dlp and AssemblyAI code.
  2. Scans `audio_cache/` for any `*_semantic.json` generated by Google AI Studio.
  3. Returns a flat list of these perfectly-sliced semantic chunks.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from . import config

logger = logging.getLogger(__name__)

_VIDEO_URL_BY_ID = {video["id"]: video["url"] for video in config.VIDEOS}


def _extract_source_file_id(file_path: Path) -> str:
    suffix = "_transcript"
    stem = file_path.stem
    return stem[:-len(suffix)] if stem.endswith(suffix) else stem


def run_ingestion() -> list[dict[str, Any]]:
    """
    Look for `.json` files in the `llm_chunks/` cache.
    Parse them, and return a single monolithic list of chunks ready for indexing.
    """
    cache_dir = Path("llm_chunks")
    if not cache_dir.exists():
        cache_dir.mkdir(parents=True, exist_ok=True)
        
    semantic_files = sorted(cache_dir.glob("*.json"))
    
    if not semantic_files:
        logger.warning(
            "\n⚠️ No `.json` files found in `%s/`.\n"
            "   Please upload your MP3s to Google AI Studio, run the prompt from \n"
            "   `ai_studio_prompt.md`, and save the results here.\n"
            "   Until you do this, there's no data to embed!",
            cache_dir.name
        )
        return []

    all_chunks: list[dict[str, Any]] = []

    for file_path in semantic_files:
        logger.info("[run_ingestion] Loading semantic chunks from: %s", file_path.name)
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                chunks = json.load(f)
                
            if not isinstance(chunks, list):
                logger.error("File %s must contain a JSON array of objects.", file_path.name)
                continue

            source_file_id = _extract_source_file_id(file_path)
            fallback_url = _VIDEO_URL_BY_ID.get(source_file_id)

            for chunk in chunks:
                if not isinstance(chunk, dict):
                    continue
                enriched_chunk = dict(chunk)
                enriched_chunk.setdefault("source_file_id", source_file_id)
                if fallback_url:
                    enriched_chunk.setdefault("youtube_url", fallback_url)
                all_chunks.append(enriched_chunk)
        except Exception as exc:
            logger.error("[run_ingestion] Failed to load %s: %s", file_path.name, exc)
            raise

    logger.info(
        "[run_ingestion] Successfully loaded %s semantic chunks across %s files.",
        len(all_chunks), len(semantic_files)
    )
    return all_chunks
